### ISSUE TITLE
ValueError: No font file was found.

### ISSUE THREAD

**Issue by so-karey** [NyashniyVladya/Translator3000#12]
tried to follow the instructions but whenever there is a line to translate I get an the error page for example
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1740, in script
    plr "{color=#FF69B4}{i}Центр города, да?{/i}{/color}"
  File "game/Translator3000Data/scripts/general.rpy", line 252, in __call__
  File "game/Translator3000Data/scripts/general.rpy", line 301, in _apply_enabled_text_tags
  File "game/Translator3000Data/scripts/general.rpy", line 175, in get_font
ValueError: No font file was found.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1740, in script
    plr "{color=#FF69B4}{i}Центр города, да?{/i}{/color}"
  File "F:\NSFW\Lust City - Ver.1.2_Win\renpy\ast.py", line 626, in execute
    what = renpy.config.say_menu_text_filter(what)  # E1102
  File "game/Translator3000Data/scripts/general.rpy", line 252, in __call__
  File "game/Translator3000Data/scripts/general.rpy", line 301, in _apply_enabled_text_tags
  File "game/Translator3000Data/scripts/general.rpy", line 175, in get_font
ValueError: No font file was found.

Windows-8-6.2.9200
Ren'Py 6.99.14.1.3218
LustCity.Beta 1.2.Beta.Little_horns.update
Tue Feb 16 20:39:21 2021
[/code]

**Comment by NyashniyVladya** [comment]
Can I see the contents of the settings file?

**Comment by so-karey** [comment]
{
    "translationService": "google", 
    "_debug_mode": false, 
    "extraTextOptions": {
        "font": "my_font.ttf", 
        "bold": false, 
        "italic": false, 
        "size": "+10"
    }, 
    "requestsFrequency": 100.57142857142858, 
    "originalInHistory": false, 
    "directionOfTranslation": "en", 
    "prescan": false, 
    "gameLanguage": "ru"
}

**Comment by NyashniyVladya** [comment]
The example given in the instructions is only a demonstration. It does not need to be copied in its entirety. Detailed descriptions of all items are also described in the manual.
In your case, you specified in the settings the font "my_font.ttf", which is not in the game files.

Set the key **_"font"_** to **_null_**, start the game and adjust the settings in the GUI.

**Comment by so-karey** [comment]
well that is strange, as I didn't really copy anything, I only adjusted the settings from the GUI and it added that part. 
I even tried to delete the extraTextOptions part but that didn't work.

Changing the "font" to null did work though, Thanks !
