### ISSUE TITLE
I'm sorry, but an uncaught exception occurred.

### ISSUE THREAD

**Issue by Enlyz** [NyashniyVladya/Translator3000#13]
![erro](https://user-images.githubusercontent.com/77436403/108846520-6cd37c00-75bd-11eb-993d-d9d3cf469fb6.png)

Hello. This "I'm sorry, but an uncaught exception occurred." is happening to me when using the current 'Translator3000' and 2 version ago. what is the reason for this error? this happened to me with some games, and some who could use the program normally but with the new version of the game the same error appeared. is it possible for the user to resolve this error?

**Comment by NyashniyVladya** [comment]
Hello. The version of Ren'Py in the games where the error occurs is 7.4.x? If so, I will be releasing a compatibility update with these versions soon.

**Comment by Enlyz** [comment]
It was really compartability. thank you for making this incredible tool available to everyone.
