### ISSUE TITLE
Support Ren'Py- 7.4.2

### ISSUE THREAD

**Issue by DusanRemec** [NyashniyVladya/Translator3000#14]
Привет!
В первую очередь, спасибо тебе автор, за данное расширение для движка Ren Py.
Благодаря твоему творению, я могу играть в иностранные игры на родном языке.

Но в последнее время, Translator3000 всё чаще перестает работать в играх на этом движке.
Причина банальна, разработчики переходят на новую версию движка под номером 7.4.2, которая уже вышла из бета теста.

Следовательно, возникает вопрос: **"Будет осуществлена ли поддержка данной версии и когда?"**

**Comment by NyashniyVladya** [comment]
Будет. В ближайшее время. Даты точнее назвать не могу. Разгребу дела насущные и сразу займусь.

**Comment by DusanRemec** [comment]
Cпасибо за ответ!
