### ISSUE TITLE
Self-voice enabled repeat "Translator3000 version 2.7.0" and then narrate

### ISSUE THREAD

**Issue by xandyxp** [NyashniyVladya/Translator3000#19]
Whenever I leave Self-voice enabled
Before speaking text, say "Translator3000 version 2.7.0" and start.
The problem is that whenever I advance in the texts, it returns again before the dialogue to say on the voice active says "Translator3000 version 2.7.0"

Any game that i play with voice active happens this situation.
ends narrates dialogue, and move on to the next dialogue he repeats before the dialogue says "Translator3000 version 2.7.0"

Is there anything that can help me solve this problem

**Comment by NyashniyVladya** [comment]
Fixed in 2.7.0.

**Comment by xandyxp** [comment]
@NyashniyVladya 
Thank you very much for your work and attention, looking for improvements to make the experience as pleasant as possible.
I did a test in version 2.7.1 it was perfect.
