### ISSUE TITLE
Translator3000  It has not worked for 2 days

### ISSUE THREAD

**Issue by paloslios** [NyashniyVladya/Translator3000#2]
first of all thank you for your great work.
translator3000 is a fantastic program that I have recommended to many people.
These same people are the ones who have warned me that it has not worked for 2 days.

Thank you so much for everything

**Comment by NyashniyVladya** [comment]
Thank you for the report. I already know about the problem, it is related to the fact that Google has completely changed the token generation algorithm. In the coming days I will adapt the software to the new logic.

**Comment by paloslios** [comment]
Thank you very much for your work, me and my colleagues
we will be attentive to your news.
Greetings

**Comment by NyashniyVladya** [comment]
Updated. You can download new version from the [release page](https://github.com/NyashniyVladya/Translator3000/releases).

**Comment by paloslios** [comment]
Thank you very much for your work and effort

Greetings
