### ISSUE TITLE
translation to Spanish

### ISSUE THREAD

**Issue by paloslios** [NyashniyVladya/Translator3000#5]
as you said

If there are native speakers of other languages who are willing to help translate this instruction into their language, I will be happy to add their translations. Thank you!

here I put it in Spanish in case you want to add it

https://f95zone.to/threads/lista-de-juegos-en-espanol-spanish-games.31851/post-4670843

thank you very much again for your great work

**Comment by NyashniyVladya** [comment]
Thank you for your feedback! I looked at the post on your link. It's more of a short description, but I'd like to make a more complete manual like the one currently available on the release page. If you help me with this, it would be great.

You also described the options for the settings file a bit wrong (as far as I could tell from the Spanish-Russian translation).
"_debug_mode" has no effect on saving the translation. The translation will be saved in an external file anyway. If "_debug_mode" is true, the log file will be written and exceptions will be raised. The mode affects only this.
But this inaccuracy is entirely my fault. I should have done the English version of the instruction earlier. Until you wrote me (in your previous post), I didn't think the project was interesting to anyone from other countries. I am glad that I was wrong about it.

**Comment by caedus12** [comment]
Good I like your program at last I can play my games in my language, a question how do I save the translation of a complete game, suddenly the internet can go away, oh update the visual novel

**Comment by NyashniyVladya** [comment]
> it's a great program, can I play my games in my language, one question, how do I save the translation of a full game? Suddenly, the Internet can disappear. Oh, update the visual novel. I am using a language translator, sorry if it is not well understood

You don’t need to worry about saving the translated data. The translation is saved automatically: after every query in the normal mode, and every hundredth query in the prescan mode.
The translation is saved in a folder unrelated to a particular game and is the same for all games.
If you translate the **_X_** phrase in one Ren'Py game, it will be loaded when you start another one.
The database is stored here: **_%userprofile%\vladya's projects database\translator3000\Google\1.1_**

**Comment by NyashniyVladya** [comment]
Senyu, thank you for your kind words. To know that my work is really useful for someone is very motivating. It's true.

**Comment by NyashniyVladya** [comment]
**_A little off-top:_** For some reason I couldn't see your message earlier, although it was written 4 days ago. I only saw it today, after **caedus12**'s comment. Before that, the message counter was equal to 1. This is strange. GitHub has always worked steadily...

**Comment by caedus12** [comment]
sometimes a game is slow when it translates you know how to solve it

**Comment by NyashniyVladya** [comment]
> sometimes a game is slow when it translates you know how to solve it

Freezes during real-time translation are unavoidable. Plus, do not forget about the pause between requests to the translation service. The pause is necessary, that actions for service look as actions of the real person in a browser.
This happens only the first time you translate a phrase that is not yet in the database. As I wrote above, the data is cached, so freezes on re-reading will not. You can also enable pre-scan mode (instructions are [on the release page](https://github.com/NyashniyVladya/Translator3000/releases)) - in this case, the text will be translated in advance.
