### ISSUE TITLE
Translator3000 Version 2.9.5

### ISSUE THREAD

**Issue by By-PorfecTo** [NyashniyVladya/Translator3000#51]
currently working

(https://s2.dosya.tc/server16/i5yyr3/Translator3000.rar.html)

**Comment by DA6KLI9HT** [comment]
> currently working
> 
> (https://s2.dosya.tc/server16/i5yyr3/Translator3000.rar.html)

God thank u very much, idk why but i cant download v2.9.5 from NyashniyVladya and 2.9.6 working with lags. Dude really thanks :) 2.9.5 seems ok :)

**Comment by By-PorfecTo** [comment]
google translate has restricted it catches the translation program and prevents it from working so 2.9.6 does not work
It works with vpn for a maximum of 1 minute, I hope the problem will be resolved as soon as possible.

English is not my mother tongue, sorry if I speak badly

**Comment by DA6KLI9HT** [comment]
> google translate has restricted it catches the translation program and prevents it from working so 2.9.6 does not work It works with vpn for a maximum of 1 minute, I hope the problem will be resolved as soon as possible.
> 
> English is not my mother tongue, sorry if I speak badly

Yeah, hope they won't block translator in future
