### ISSUE TITLE
Увы, перестало работать

### ISSUE THREAD

**Issue by Veres96** [NyashniyVladya/Translator3000#6]
Привет. Это очень полезный код для людей без знания языка. Я наткнулся на него абсолютно случайно и она класно работала до последних обновлений. Все внезапно заглохло и я понял, что вышло обновление. До этого вообще не надо было ничего писать в set., достаточно было бросить tr3000 в папку Game. Сейчас к сожалению в большинстве игр перевод не работает (версии до 7.4). Либо совсем, либо переводит на кракозябры и точки (возможно не разбирает шрифты как в XUnity.AutoTranslator).

**Comment by NyashniyVladya** [comment]
Доброго времени суток. После Вашего сообщения я ещё раз всё перепроверил и действительно нашёл ошибку, из за которой проект некорректно работал в режиме предварительного сканирования.
Обновление, исправляющее это, уже на странице релизов.
Если не поможет - включите опцию **__debug_mode_** в настройках и скиньте мне трейсбек, который вылетит при ошибке. Будем разбираться в чём дело.

> либо переводит на кракозябры и точки

Подобное действительно возможно в ситуациях, когда шрифт не содержит имеющихся в переводе символов. Для разрешения подобных проблем, я добавил в настройки опцию **_["extraTextOptions"]["font"]_**. Как именно указывать шрифт - так же описано на странице релизов.
