### ISSUE TITLE
Как мне связаться с создателем?

### ISSUE THREAD

**Issue by K14Mua** [NyashniyVladya/Translator3000#69]
![image](https://user-images.githubusercontent.com/24901436/219756951-60090c06-e81b-4ded-acfe-21276125f3d6.png)
На бусти ЛС закркыты.

![image](https://user-images.githubusercontent.com/24901436/219757052-9a6e2489-7e31-4502-82a2-cf639076b446.png)
Комментарий тоже написать нельзя. 

![image](https://user-images.githubusercontent.com/24901436/219757138-0612f1c2-ec9d-4225-908a-68e6eb924e87.png)
Хотя подписка куплена.

![image](https://user-images.githubusercontent.com/24901436/219757180-5dc4640c-f22e-404b-b8cf-cf2d140c5f02.png)
В дискорде меня забанил и даже в друзья его никак не добавить.

![image](https://user-images.githubusercontent.com/24901436/219757352-fa819231-99e3-44b0-bb72-4e0e135baf86.png)
Второй аккаунт тоже заблокировал и писать я ему там не могу

![image](https://user-images.githubusercontent.com/24901436/219757395-596c855d-0792-407a-9b4f-eb450b6b90a6.png)
Третий аккаунт сделал, и зашел на сервер, тут же заблокировал и не могу даже на сервере ничего написать.

Это что за тотальный игнор? Нормально же общались. Осталось только тут заблокировать для полного счастья.

**Comment by NyashniyVladya** [comment]
Интересная тактика, выставить себя "жертвой" перед публикой... Не пойму только, зачем оно Вам нужно, но, видимо, зачем-то...
Только упомянуть, что оскорбляли меня вы, видимо, забыли... За что и в бан попали. То что связаться Вы со мной не можете - тоже ложь. С одного из фейков Вы мне написали, но молчите, Вам публика, видимо, нужна.
Уж не знаю, за что Вы меня и мой проект так возненавидели, что даже на подписку ради хейта потратились, но это грустно, как-то, что ли...

**Comment by K14Mua** [comment]
> Интересная тактика, выставить себя "жертвой" перед публикой... Не пойму только, зачем оно Вам нужно, но, видимо, зачем-то... Только упомянуть, что оскорбляли меня вы, видимо, забыли... За что и в бан попали. То что связаться Вы со мной не можете - тоже ложь. С одного из фейков Вы мне написали, но молчите, Вам публика, видимо, нужна. Уж не знаю, за что Вы меня и мой проект так возненавидели, что даже на подписку ради хейта потратились, но это грустно, как-то, что ли...

На скриншот посмотри. Видишь сообщения от дискорда? Я не могу там больше писать. И заявки в друзья от других аккаунтов ты тоже не принимаешь. Я "выставляю перед публикой" по тому что никакого другого способа связи не осталось. Ты все каналы обрезал. За что возненавидел? За тотальный игнор. Я же пытался решить все мирно. А ты и в ЛС меня заблокировал, и на бусти, и все аккаунты в дискорде. Что мне еще остается делать? Вытащи аккаунт из ЧС или прими предложение дружбы от другим. Там и поговорим.

**Comment by NyashniyVladya** [comment]
Либо Вы лукавите, либо Дискорд с ума сошёл. Я Вас там не банил, а ждал ответа.
![IMG_20230217_221531.jpg](https://user-images.githubusercontent.com/19994753/219766373-763312a1-e966-4e23-a009-354ffdfad84f.jpg)

**Comment by K14Mua** [comment]
И лично я не считаю это оскорблением. Я писал это сообщения не с целью оскорбления. Для этого в моем лексиконе есть куда более жесткие выражения.

![image](https://user-images.githubusercontent.com/24901436/219767553-9e16e63c-a7ef-4474-8724-c6d891aa82b8.png)

**Comment by NyashniyVladya** [comment]
И скрин из браузера, где легко поменять исходный код... Не банил я Вас с этого акка. Хотя, если Вы исходный код подменили, Вы итак это знаете...
![IMG_20230217_222817.jpg](https://user-images.githubusercontent.com/19994753/219769097-c899e648-d114-4a07-98d1-08fa9f7d5542.jpg)

**Comment by K14Mua** [comment]
> И скрин из браузера, где легко поменять исходный код... Не банил я Вас с этого акка. Хотя, если Вы исходный код подменили, Вы итак это знаете... ![IMG_20230217_222817.jpg](https://user-images.githubusercontent.com/19994753/219769097-c899e648-d114-4a07-98d1-08fa9f7d5542.jpg)

Ну вот и что мне делать?

**Comment by K14Mua** [comment]
Скрин из браузера по тому что в клиенте у меня мой основной аккаунт который в бане, и запросы дружбы ты не принимаешь даже от тех кто на одном сервере с тобой. Этот запрос чудом как то проскочил но не надолго. Мне с тобой теперь через гитхаб только общаться?

**Comment by NyashniyVladya** [comment]
Сейчас открою запросы... Попробуйте с основного добавиться.

Если Вы сейчас не лукавите и действительно не можете мне написать, то я совершенно без понятия почему это происходит. Может, автозащита от дискорда...
