### ISSUE TITLE
Цвет и курсив

### ISSUE THREAD

**Issue by MrAbsolutely** [NyashniyVladya/Translator3000#8]
Привет. У меня вопрос: программа работает хорошо (да, некоторые игры не захватывает, но это не важно, темы я прочитал почему), но она не отображает курсив и не меняет цвет текста.
![image](https://user-images.githubusercontent.com/76562337/103093646-bdaa1100-461c-11eb-9053-53854f9b0615.png)

Так же еще один вопрос: а можно ли отключать переводчик самому в игре по нажатию кнопки? И можно такое сделать?

**Comment by NyashniyVladya** [comment]
> она не отображает курсив и не меняет цвет текста

Есть такое. А ещё удаляет текстовые теги вида **_{w}_**/**_{nw}_** и подобные.
Это сделано, потому что теги нельзя экранировать, при обращении к сервису перевода и сервис вполне может перевести **_{i}_**, как **_{и}_**, или иначе; что, разумеется, приведёт к ошибке. Можно, конечно, переводить частями (отрывок до тега, отрывок после него и т.д.), но в этом случае сильно пострадает качество самого перевода, т.к. слова переведутся без учёта всего контекста и будут не связаны между собой.
В общем, я не вижу способа "безболезненно" сохранить теги, поэтому принял решение убрать их вообще.

> а можно ли отключать переводчик самому в игре по нажатию кнопки? И можно такое сделать?

На данный момент - нет. Добавил себе в TODO лист. Сделаю в новых версиях.

**Comment by MrAbsolutely** [comment]
Понял.

**Comment by NyashniyVladya** [comment]
> > а можно ли отключать переводчик самому в игре по нажатию кнопки? И можно такое сделать?
> 
> На данный момент - нет. Добавил себе в _TODO list_. Сделаю в новых версиях.

Возможность добавлена в последнем обновлении (2.5.4.).
