### ISSUE TITLE
Problem saving game progress...

### ISSUE THREAD

**Issue by Senyu** [NyashniyVladya/Translator3000#9]
![](https://i.imgur.com/jw1QJ7d.png)
In some games I tested the new version (2.5.4) and they all presented the same error when saving the game progress.

Some the error happened only after changing the name of the game's MC (main character) and in some other games only after some character event.

Oh! And I found it very interesting what was done in this version:
![](https://i.imgur.com/tp73dpL.png)

Very nice of you to implement in game this, thank you!

PS: Oh! And... is it possible to hide the update message for Translator3000 in version 2.4.13 so that it doesn't show up?
I still have this version and since version 2.5.4 has the problem of saving, I'm used it again 2.4.13... it would be nice to be able to hide the message if the person does not want to update at the moment.

PS2: Well the only way I found for the update message not to appear is to disable the internet, start the game and then activate the internet again for the update message not to appear.
Well, it works for me for now, but once the version problem 2.5.4 is resolved I must update.

**Comment by NyashniyVladya** [comment]
The saving bug was fixed in the latest update.


> PS: Oh! And... is it possible to hide the update message for Translator3000 in version 2.4.13 so that it doesn't show up?

In version 2.4.13, this functionality has not yet been implemented. In new versions, you can hide the window by clicking the button in the upper right corner.

**Comment by Senyu** [comment]
Thank you for fixed the problem with the saving, I already tested the new version (2.5.6) with some games and I didn't find any problem/bug.
